import re
from langchain_core.messages import HumanMessage
from graph import app

def main():
    print("\n🎓 Welcome to the Socratic Tutor (ReAct Mode)!")
    print("The agent will now autonomously decide when to search the curriculum and when to evaluate you.")
    print("Type 'quit' or 'exit' to end the session.\n")
    
    # Initialize the student's conversation history
    messages = []
    
    while True:
        # 1. Get student input
        user_input = input("\n🧑‍🎓 You: ")
        if user_input.lower() in ['quit', 'exit']:
            print("Session ended. Great studying!")
            break
            
        messages.append(HumanMessage(content=user_input))
        
        # 2. Stream the Graph Execution
        print("") # formatting line
        for event in app.stream({"messages": messages}):
            for node_name, node_state in event.items():
                
                # Get the absolute latest message generated by the current node
                latest_message = node_state["messages"][-1]
                
                # If the Agent Node just ran:
                if node_name == "agent":
                    if latest_message.tool_calls:
                        # The AI decided it needs a tool!
                        for tool_call in latest_message.tool_calls:
                            print(f"🧠 [Agent Action] Triggering tool: {tool_call['name']}")
                    else:
                        # Extract the thoughts and the actual response using Regex
                        content = latest_message.content
                        
                        # Find everything inside <think> tags
                        thoughts = re.findall(r'<think>(.*?)</think>', content, flags=re.DOTALL)
                        for thought in thoughts:
                            print(f"\n💭 [Agent's Internal Monologue]:\n{thought.strip()}")
                            
                        # Remove the <think> blocks to get the clean response
                        clean_response = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL).strip()
                        
                        if clean_response:
                            print(f"\n🤖 Tutor: {clean_response}")
                
                # If the Tool Node just ran:
                elif node_name == "tools":
                    print(f"⚙️  [Tool Executed] Retrieved data successfully.")
        
        # 3. Update the global history with the new state
        messages = node_state["messages"]

if __name__ == "__main__":
    main()